\set ON_ERROR_STOP on

-- Migration: Lab 3 - add invoice discounts, totals, and VAT configuration.
-- Run this script to upgrade an existing Lab 2/Lab 8 database without recreating it.
-- Example usage: psql $DATABASE_URL -f database/sql/004_invoice_lab3_delta.sql

create table if not exists configuration (
  id bigint primary key generated by default as identity,
  created_at timestamp default now(),
  vat_percent numeric(5,4) not null default 0.07
);

-- Keep exactly one default configuration row for VAT.
insert into configuration (vat_percent)
select 0.07
where not exists (select 1 from configuration);

alter table invoice_line_item
  add column if not exists line_discount_percent numeric(5,4) not null default 0,
  add column if not exists line_discount_amount numeric(12,2) not null default 0,
  add column if not exists line_net_price numeric(12,2) not null default 0;

alter table invoice
  add column if not exists total_price numeric(12,2) not null default 0,
  add column if not exists total_discount numeric(12,2) not null default 0,
  add column if not exists net_price numeric(12,2) not null default 0,
  add column if not exists vat_percent numeric(5,4) not null default 0.07,
  add column if not exists vat_amount numeric(12,2) not null default 0;

-- Backfill the new line columns from existing Lab 2 data.
update invoice_line_item
set
  line_discount_percent = coalesce(line_discount_percent, 0),
  line_discount_amount = round(coalesce(line_discount_percent, 0) * coalesce(extended_price, 0), 2),
  line_net_price = round(coalesce(extended_price, 0) - coalesce(line_discount_amount, 0), 2);

-- Backfill invoice totals while keeping old Lab 2 columns intact.
with config as (
  select coalesce((select vat_percent from configuration order by id limit 1), 0.07) as default_vat_percent
),
invoice_totals as (
  select
    i.id,
    round(coalesce(sum(li.extended_price), 0), 2) as total_price,
    round(coalesce(sum(li.line_discount_amount), 0), 2) as total_discount
  from invoice i
  left join invoice_line_item li on li.invoice_id = i.id
  group by i.id
)
update invoice i
set
  total_price = t.total_price,
  total_discount = t.total_discount,
  net_price = round(t.total_price - t.total_discount, 2),
  vat_percent = coalesce(nullif(i.vat, 0) / nullif(coalesce(i.total_amount, t.total_price), 0), i.vat_percent, config.default_vat_percent),
  vat_amount = round((t.total_price - t.total_discount) * coalesce(nullif(i.vat, 0) / nullif(coalesce(i.total_amount, t.total_price), 0), i.vat_percent, config.default_vat_percent), 2),
  amount_due = round((t.total_price - t.total_discount) + round((t.total_price - t.total_discount) * coalesce(nullif(i.vat, 0) / nullif(coalesce(i.total_amount, t.total_price), 0), i.vat_percent, config.default_vat_percent), 2), 2)
from invoice_totals t
cross join config
where i.id = t.id;

