\set ON_ERROR_STOP on

-- Lab 04 delta: add receipt transaction tables and invoice_received view.
-- This script is safe to apply to an existing InvoiceDoc2 database.

create table if not exists receipt (
  id bigint primary key generated by default as identity,
  created_at timestamp default now(),
  receipt_no text unique not null,
  receipt_date date not null,
  customer_id bigint not null references customer(id),
  payment_method text not null,
  payment_notes text,
  total_received numeric(12,2) not null default 0,
  constraint receipt_payment_method_chk
    check (payment_method in ('cash', 'bank transfer', 'check')),
  constraint receipt_total_received_chk
    check (total_received >= 0)
);

create table if not exists receipt_line_item (
  id bigint primary key generated by default as identity,
  created_at timestamp default now(),
  receipt_id bigint not null references receipt(id) on delete cascade,
  invoice_id bigint not null references invoice(id),
  amount_received numeric(12,2) not null,
  constraint receipt_line_item_amount_received_chk
    check (amount_received >= 0),
  constraint receipt_line_item_receipt_invoice_uniq
    unique (receipt_id, invoice_id)
);

create index if not exists idx_receipt_date on receipt(receipt_date);
create index if not exists idx_receipt_customer on receipt(customer_id);
create index if not exists idx_receipt_line_receipt on receipt_line_item(receipt_id);
create index if not exists idx_receipt_line_invoice on receipt_line_item(invoice_id);

create or replace view invoice_received as
select
  i.customer_id,
  i.id as invoice_id,
  i.invoice_no,
  i.amount_due,
  coalesce(sum(rli.amount_received), 0::numeric(12,2)) as amount_received,
  i.amount_due - coalesce(sum(rli.amount_received), 0::numeric(12,2)) as amount_remain
from invoice i
left join receipt_line_item rli on rli.invoice_id = i.id
group by i.customer_id, i.id, i.invoice_no, i.amount_due;
